{
'name': 'Prisme Timesheet Enhancement',
'version': '2017-07-03 12:10',
'category': 'Human Resources',
'summary': 'start / end time, reports',
'author': 'Prisme Solutions Informatique SA',
'website': 'http://www.prisme.ch',
'depends': [
        'hr_timesheet',
        'hr_timesheet_sheet',
        'hr_timesheet_attendance',
        ],
'init_xml': [],
    'update_xml': [
        'view/view_hr_timesheet_line.xml',
        'view/view_hr_timesheet_sheet.xml',
        'view/view_account_analytic_line.xml',
        'view/timesheet_grid.xml',
        'report/templates/hr_timesheet_sheet_check.xml',
        'report/templates/account_analytic_line.xml',
        'report/templates/account_invoice_detail.xml',
        'view/hr_timesheet_invoice_factor.xml',
        'view/account_analytic_account.xml',
        'view/hr_employee.xml',
        'wizard/hr_timesheet_invoice_create_view.xml',
        'view/view_project_project.xml',
        'security/ir.model.access.csv',
    ],
    'demo_xml': [],
    'test': [],
    'installable': True,
    'active': False,
	'application': True,
}
