{
    "name": "Prisme Client Accounting Line",
    "version": "2020-04-27 14:00",
    "author": "Prisme Solutions Informatique SA",
    "category": "Generic Modules/Accounting",
    "website": "https://www.prisme.ch",
    "summary": "List of client accounting lines",
    "depends": [
        'account',
    ],
    "demo": [],
    "data": [
        "view/view_accounting_line_client.xml",
        "view/view_invoice_line_form.xml",
    ],
    'images':[
        'static/images/main_screenshot.png',
    ],
    "test": [],
    "js": [],
    "css": [],
    "qweb": [],
    "installable": True,
    "auto_install": False,
    "active": False,
    "sequence":150,
    'price': 50,
    'currency': 'EUR',
    'license': 'LGPL-3',
}
