{
'name': 'Prisme Timesheet Enhancement',
'version': '2016-04-25 15:57',
'category': 'Human Resources',
'summary': 'start / end time, reports',
'author': 'Prisme Solutions Informatique SA',
'website': 'http://www.prisme.ch',
'depends': [
        'hr_timesheet',
        'hr_timesheet_sheet',
        'hr_timesheet_invoice',
		'report_webkit'],
'init_xml': [],
    'update_xml': [
        'view_hr_timesheet_line.xml',
        'view_hr_timesheet_sheet.xml',
        'view_account_analytic_line.xml',
        'report/header.xml',
        'report/report.xml',
    ],
    'demo_xml': [],
    'test': [],
    'installable': True,
    'active': False,
	'application': True,
}
